### ISSUE TITLE
Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#227]
```
[Warning] – 2022-02-21T11:41:13.420Z
DeprecationWarning
Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
    at MessageEmbed.setFooter (/usr/src/app/node_modules/discord.js/src/structures/MessageEmbed.js:439:17)
    at Object.play (/usr/src/app/build/client/funcs/play.js:24:10)
    at Object.execute (/usr/src/app/build/client/commands/play.js:131:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by cwchristerw** [comment]
Fixed in [f2569776dfc158650fbdbf30d677e01bf476ab69](https://github.com/warengroup/eximiabots-radiox/commit/f2569776dfc158650fbdbf30d677e01bf476ab69)
