### ISSUE TITLE
VoiceConnection Destroyed

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#26]
/usr/src/app/node_modules/@discordjs/voice/dist/VoiceConnection.js:317
            throw new Error('Cannot destroy VoiceConnection - it has already been destroyed');
                  ^

Error: Cannot destroy VoiceConnection - it has already been destroyed
    at VoiceConnection.destroy (/usr/src/app/node_modules/@discordjs/voice/dist/VoiceConnection.js:317:19)
    at Object.execute (/usr/src/app/build/client/events/voiceStateUpdate.js:16:35)
    at RadioClient.<anonymous> (/usr/src/app/build/Client.js:69:50)
    at RadioClient.emit (node:events:394:28)
    at VoiceStateUpdate.handle (/usr/src/app/node_modules/discord.js/src/client/actions/VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:132:16)

**Comment by cwchristerw** [comment]
It's probably caused by https://github.com/warengroup/eximiabots-radiox/commit/378fe97ea3bde8974e631e523c883f0a305690d3

**Comment by cwchristerw** [comment]
**Version 0.2.3**
Error: Cannot destroy VoiceConnection - it has already been destroyed
    at VoiceConnection.destroy (/usr/src/app/node_modules/@discordjs/voice/dist/VoiceConnection.js:352:19)
    at Object.execute (/usr/src/app/build/client/commands/stop.js:13:31)
    at Object.execute (/usr/src/app/build/client/events/msg.js:28:21)
    at RadioClient.<anonymous> (/usr/src/app/build/Client.js:66:37)
    at RadioClient.emit (node:events:394:28)
    at MessageCreateAction.handle (/usr/src/app/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
