### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#283]
[Error] – 2022-03-31T12:31:32.806Z
TypeError: Cannot read properties of null (reading 'id')
    at Object.execute (/usr/src/app/build/client/events/messageDelete.js:10:37)
    at RadioClient.<anonymous> (/usr/src/app/build/Client.js:70:47)
    at RadioClient.emit (node:events:526:28)
    at MessageDeleteAction.handle (/usr/src/app/node_modules/discord.js/src/client/actions/MessageDelete.js:24:16)
    at Object.module.exports [as MESSAGE_DELETE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_DELETE.js:4:32)
    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:526:28)

**Comment by cwchristerw** [comment]
Fixed in [#8d12a8369168022419447759613578f052d33c7c](https://github.com/warengroup/eximiabots-radiox/commit/8d12a8369168022419447759613578f052d33c7c)
