### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#284]
[Error] – 2022-03-27T13:49:02.965Z
TypeError: Cannot read properties of null (reading 'get')
    at Object.execute (/usr/src/app/build/client/events/voiceStateUpdate.js:9:36)
    at RadioClient.<anonymous> (/usr/src/app/build/Client.js:76:50)
    at RadioClient.emit (node:events:390:28)
    at VoiceStateUpdate.handle (/usr/src/app/node_modules/discord.js/src/client/actions/VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)

**Comment by cwchristerw** [comment]
Fixed in [3654dd58babad3732e4fe1e621ffccedaff32e73](https://github.com/warengroup/eximiabots-radiox/commit/3654dd58babad3732e4fe1e621ffccedaff32e73)
