### ISSUE TITLE
AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#285]
[Error] – 2022-03-27T13:48:49.821Z
AbortError: The user aborted a request.
    at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:201:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (/usr/src/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5)

**Comment by cwchristerw** [comment]
@MatteZ02 Do you know, what might cause this?
