### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'send')

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#286]
[Error] – 2022-03-25T12:05:31.180Z
TypeError: Cannot read properties of undefined (reading 'send')
    at Object.play (/usr/src/app/build/client/funcs/play.js:47:49)
    at /usr/src/app/build/client/classes/Radio.js:60:30

**Comment by cwchristerw** [comment]
Fixed in [bf7336ae8da9155bc611b63c7eb861c738b0f2e1](https://github.com/warengroup/eximiabots-radiox/commit/bf7336ae8da9155bc611b63c7eb861c738b0f2e1)
