### ISSUE TITLE
Error [CHANNEL_NOT_CACHED]: Could not find the channel where this message came from in the cache!

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#287]
[Error] – 2022-03-25T12:05:12.418Z
Error [CHANNEL_NOT_CACHED]: Could not find the channel where this message came from in the cache!
    at Message.delete (/usr/src/app/node_modules/discord.js/src/structures/Message.js:791:30)
    at Map.save (/usr/src/app/build/client/classes/Radio.js:17:45)
    at Object.execute (/usr/src/app/build/client/events/SIGINT.js:7:22)
    at process.<anonymous> (/usr/src/app/build/Client.js:84:40)
    at process.emit (node:events:390:28)
    at Object.execute (/usr/src/app/build/client/events/uncaughtException.js:10:17)
    at process.<anonymous> (/usr/src/app/build/Client.js:90:51)
    at process.emit (node:events:390:28)
    at process._fatalException (node:internal/process/execution:164:25)
    at processPromiseRejections (node:internal/process/promises:246:11)

**Comment by cwchristerw** [comment]
@MatteZ02 Do you know, what might cause this?
