### ISSUE TITLE
Leaving bot in voice channel alone will crash bot

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#3]
```
/mnt/c/Users/User/Downloads/eximiabots-radiox/events/voiceStateUpdate.js:26
                    radio.connection.dispatcher.destroy();
                                                ^

TypeError: Cannot read property 'destroy' of null
    at Timeout._onTimeout (/mnt/c/Users/User/Downloads/eximiabots-radiox/events/voiceStateUpdate.js:26:49)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

/home/user/.npm/_logs/2020-03-09T13_07_16_500Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.2
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle radiox@1.0.0~prestart: radiox@1.0.0
6 info lifecycle radiox@1.0.0~start: radiox@1.0.0
7 verbose lifecycle radiox@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle radiox@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt$9 verbose lifecycle radiox@1.0.0~start: CWD: /mnt/c/Users/User/Downloads/eximiabots-radiox
10 silly lifecycle radiox@1.0.0~start: Args: [ '-c', 'node .' ]
11 silly lifecycle radiox@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle radiox@1.0.0~start: Failed to exec start script
13 verbose stack Error: radiox@1.0.0 start: `node .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:$13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:$13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid radiox@1.0.0
15 verbose cwd /mnt/c/Users/User/Downloads/eximiabots-radiox
16 verbose Linux 4.4.0-18362-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.16.1
19 verbose npm  v6.14.2
20 error code ELIFECYCLE
21 error errno 1
22 error radiox@1.0.0 start: `node .`
22 error Exit status 1
23 error Failed at the radiox@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by cwchristerw** [comment]
This was fixed by @MatteZ02 

https://github.com/warengroup/eximiabots-radiox/commit/716786e296165b5ca9c3b3ec973b2904234dc1de
