### ISSUE TITLE
DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#37]
/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async MessageManager.delete (/usr/src/app/node_modules/discord.js/src/managers/MessageManager.js:205:5)
    at async Message.delete (/usr/src/app/node_modules/discord.js/src/structures/Message.js:709:5) {
  method: 'delete',
  path: '/channels/676514350831501334/messages/883162601650012240',
  code: 50013,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}

**Comment by cwchristerw** [comment]
https://github.com/warengroup/eximiabots-radiox/blob/3ec1892a0935aa75d142cd15f1b2760ca2fe49a5/src/client/events/messageCreate.js#L44
Tried to delete original message due to typo
