### ISSUE TITLE
Using volume command when not connected

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#5]
There some problems with volume command.

`rx-volume`
There is nothing playing!
You need to enter a valid number.

`rx-volume 10`
There is nothing playing!
@cwchristerw, Running this command failed!

IN CONSOLE
```
TypeError: Cannot set property 'volume' of undefined
    at Object.execute (/mnt/c/Users/User/Downloads/eximiabots-radiox/commands/volume.js:21:17)
    at Object.execute (/mnt/c/Users/User/Downloads/eximiabots-radiox/events/msg.js:16:21)
    at module.exports.<anonymous> (/mnt/c/Users/User/Downloads/eximiabots-radiox/struct/client.js:34:37)
    at module.exports.emit (events.js:311:20)
    at MessageCreateAction.handle (/mnt/c/Users/User/Downloads/eximiabots-radiox/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/mnt/c/Users/User/Downloads/eximiabots-radiox/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/mnt/c/Users/User/Downloads/eximiabots-radiox/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/mnt/c/Users/User/Downloads/eximiabots-radiox/node_modules/discord.js/src/client/websocket/WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (/mnt/c/Users/User/Downloads/eximiabots-radiox/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/mnt/c/Users/User/Downloads/eximiabots-radiox/node_modules/ws/lib/event-target.js:120:16)
```

Expected
`rx-volume`
There is nothing playing!

`rx-volume 10`
There is nothing playing!

**Comment by cwchristerw** [comment]
Fixed by cwchristerw
https://github.com/warengroup/eximiabots-radiox/commit/a6e8efedf6afc3218f886f100bf02541196a0261
