### ISSUE TITLE
DiscordAPIError: Unknown interaction

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#68]
[Error] – 2021-09-15T18:12:20.269Z
```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async CommandInteraction.reply (/usr/src/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5)```

**Comment by cwchristerw** [comment]
```
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:736:23)
    at async REST.request (/usr/src/app/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async StringSelectMenuInteraction.reply (/usr/src/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
```
