### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'error')

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#69]
[Error] – 2021-09-15T18:12:35.463Z
```
TypeError: Cannot read properties of undefined (reading 'error')
    at Object.execute (/usr/src/app/build/client/commands/play.js:15:46)
    at Object.execute (/usr/src/app/build/client/events/interactionCreate.js:19:25)
    at RadioClient.<anonymous> (/usr/src/app/build/Client.js:82:51)
    at RadioClient.emit (node:events:394:28)
    at InteractionCreateAction.handle (/usr/src/app/node_modules/discord.js/src/client/actions/InteractionCreate.js:66:12)
    at Object.module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:132:16)```

**Comment by cwchristerw** [comment]
Possible fix is https://github.com/warengroup/eximiabots-radiox/pull/63/commits/bfb27e735914b659b76bfde94208d02f0fa36e0a

**Comment by cwchristerw** [comment]
This was caused by user writing command before messageEmojis was loaded. Error emoji was missing from messageEmojis array.
