### ISSUE TITLE
SyntaxError: /usr/src/app/datastore/000000000000000000.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#76]
SyntaxError: /usr/src/app/datastore/000000000000000000.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1167:22)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at module.exports.loadEntry (/usr/src/app/build/client/classes/Datastore.js:49:22)
    at module.exports.checkEntry (/usr/src/app/build/client/classes/Datastore.js:30:14)
    at Object.execute (/usr/src/app/build/client/commands/play.js:123:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by cwchristerw** [comment]
https://github.com/warengroup/eximiabots-radiox/blob/0945c7c26c042cac32a8f2a08b166b849bbac8c2/src/client/classes/Datastore.js#L50-L53
